import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  dashboardContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
  },
  kpiGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '24px',
  },
  kpiCard: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '24px 30px',
  },
  kpiInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  kpiLabel: {
    fontSize: '0.8rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: 'var(--text-secondary)',
  },
  kpiValue: {
    fontSize: '2.2rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-display)',
    lineHeight: 1,
  },
  kpiIcon: {
    width: '48px',
    height: '48px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomSection: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '24px',
  },
  feedCard: {
    padding: '30px',
    display: 'flex',
    flexDirection: 'column',
  },
  cardHeader: {
    marginBottom: '24px',
  },
  cardTitle: {
    fontSize: '1.1rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  cardSubtitle: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
  },
  loadingText: {
    color: 'var(--text-muted)',
    fontSize: '0.9rem',
    padding: '20px 0',
    textAlign: 'center',
  },
  membersList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  memberItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    padding: '12px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid rgba(255, 255, 255, 0.02)',
    background: 'rgba(255, 255, 255, 0.01)',
  },
  avatarLetter: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    background: 'var(--accent-glow)',
    border: '1px solid rgba(99, 102, 241, 0.3)',
    color: 'var(--accent-hover)',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textTransform: 'uppercase',
  },
  avatarImage: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '1px solid rgba(99, 102, 241, 0.3)',
  },
  memberDetails: {
    flex: 1,
  },
  memberName: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  memberSub: {
    fontSize: '0.75rem',
    color: 'var(--text-secondary)',
  },
  dateLabel: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
  },
  emptyFeed: {
    padding: '40px 0',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    color: 'var(--text-secondary)',
  },
  quickActionsCard: {
    padding: '30px',
    height: 'fit-content',
  },
  actionButtons: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
  },
  shortcutBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    padding: '16px',
    borderRadius: 'var(--radius-sm)',
    border: '1px solid var(--border)',
    background: 'rgba(255, 255, 255, 0.01)',
    color: 'var(--text-primary)',
    cursor: 'pointer',
    textAlign: 'left',
    transition: 'all var(--transition-fast)',
  },
  shortcutText: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
  },
  shortcutBtnSecondary: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '10px',
    borderRadius: 'var(--radius-sm)',
    border: '1px dashed var(--border)',
    background: 'transparent',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontWeight: 500,
    transition: 'all var(--transition-fast)',
  },
  emptyContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '60vh',
  },
  emptyCard: {
    maxWidth: '400px',
    padding: '40px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  formCard: {
    width: '100%',
    maxWidth: '480px',
    padding: '40px',
  },
  formActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '12px',
    marginTop: '24px',
  },
};
