import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    width: '100%',
  },
  tabHeaders: {
    display: 'flex',
    background: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius-sm)',
    padding: '4px',
    gap: '4px',
  },
  tabBtn: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    padding: '12px',
    background: 'transparent',
    border: 'none',
    borderRadius: 'calc(var(--radius-sm) - 2px)',
    color: 'var(--text-secondary)',
    fontSize: '0.85rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'all var(--transition-fast)',
  },
  tabBtnActive: {
    background: 'var(--bg-hover)',
    color: 'var(--text-primary)',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.2)',
  },
  formCard: {
    padding: '30px',
  },
  cardHeader: {
    marginBottom: '28px',
    borderBottom: '1px solid var(--border)',
    paddingBottom: '16px',
  },
  subtitle: {
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
    marginTop: '4px',
    lineHeight: 1.4,
  },
  textarea: {
    height: '240px',
    resize: 'vertical',
    minHeight: '180px',
  },
  formRow: {
    display: 'flex',
    gap: '16px',
  },
  alertBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '12px 16px',
    background: 'rgba(245, 158, 11, 0.05)',
    border: '1px solid rgba(245, 158, 11, 0.15)',
    borderRadius: 'var(--radius-sm)',
    marginBottom: '24px',
  },
  alertText: {
    fontSize: '0.78rem',
    color: 'var(--warning)',
  },
  submitBtn: {
    width: '100%',
    padding: '12px',
  },
  syncHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
  },
  syncTitleSection: {
    display: 'flex',
    flexDirection: 'column',
  },
  syncBtn: {
    padding: '8px 16px',
    fontSize: '0.85rem',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  publishBtn: {
    padding: '6px 12px',
    fontSize: '0.8rem',
    background: 'var(--accent)',
    color: '#fff',
    border: 'none',
    borderRadius: 'var(--radius-sm)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontWeight: 500,
    transition: 'all var(--transition-fast)',
  },
  publishedBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '4px 8px',
    background: 'var(--success-glow)',
    color: 'var(--success)',
    borderRadius: 'var(--radius-sm)',
    fontSize: '0.75rem',
    fontWeight: 600,
    border: '1px solid rgba(16, 185, 129, 0.2)',
  },
  eventLink: {
    color: 'var(--text-accent)',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '0.85rem',
  },
  spinner: {
    animation: 'spin 1s linear infinite',
  },
};
