import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  sidebar: {
    position: 'fixed',
    top: 0,
    left: 0,
    bottom: 0,
    width: 'var(--sidebar-width)',
    backgroundColor: 'var(--bg-secondary)',
    borderRight: '1px solid var(--border)',
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 16px',
    zIndex: 10,
  },
  brandContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    marginBottom: '32px',
  },
  logoCircle: {
    width: '36px',
    height: '36px',
    borderRadius: '8px',
    background: 'var(--accent-gradient)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 4px 12px rgba(99, 102, 241, 0.25)',
  },
  brandTitle: {
    fontSize: '1.15rem',
    color: 'var(--text-primary)',
    fontWeight: 600,
    lineHeight: 1.1,
  },
  brandSubtitle: {
    fontSize: '0.75rem',
    color: 'var(--text-muted)',
  },
  communitySelector: {
    padding: '12px',
    borderRadius: 'var(--radius-sm)',
    background: 'rgba(255, 255, 255, 0.02)',
    border: '1px solid var(--border)',
    marginBottom: '28px',
  },
  communityLabel: {
    fontSize: '0.7rem',
    color: 'var(--text-muted)',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '4px',
  },
  communityName: {
    fontSize: '0.85rem',
    fontWeight: 600,
    color: 'var(--accent-hover)',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  nav: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    flex: 1,
  },
  navButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 14px',
    borderRadius: 'var(--radius-sm)',
    border: 'none',
    background: 'transparent',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '0.9rem',
    fontWeight: 500,
    transition: 'all var(--transition-fast)',
  },
  navButtonActive: {
    background: 'var(--accent-glow)',
    color: 'var(--text-primary)',
  },
  icon: {
    color: 'var(--text-muted)',
    transition: 'color var(--transition-fast)',
  },
  iconActive: {
    color: 'var(--accent)',
  },
  logoutButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 14px',
    borderRadius: 'var(--radius-sm)',
    border: 'none',
    background: 'rgba(239, 68, 68, 0.05)',
    color: 'var(--error)',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '0.9rem',
    fontWeight: 500,
    transition: 'all var(--transition-fast)',
    marginTop: 'auto',
  },
  borderToggleBtn: {
    position: 'absolute',
    top: '24px',
    right: '-12px',
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    backgroundColor: 'var(--bg-secondary)',
    border: '1px solid var(--border)',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
    zIndex: 11,
    transition: 'all var(--transition-fast)',
  },
};
